version: "3.8"
services:
  mysql:
    image: mysql:latest
    # container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: adopteunprof2
      # MYSQL_USER: root
      # MYSQL_PASSWORD: azerty
      MYSQL_ROOT_PASSWORD: azerty
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  server:
    build:
      context: ./back-adopteunprof
    container_name: server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:z
      - /app/back
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    # command: sh -c "php artisan passport:install --force"

  client:
    build:
      context: ./vue-adopteunprof
    container_name: client
    ports:
      - "5000:5000"
    depends_on:
      - "server"
